### ISSUE TITLE
Cannot Install via Composer

### ISSUE THREAD

**Issue by RamzyVirani** [bryglen/yii2-validators#2]
I am getting below error when trying to install with composer. can you please look into it? 
![image](https://cloud.githubusercontent.com/assets/8522676/7083387/a6b02340-df7a-11e4-9337-6a6fbce2fa28.png)

**Comment by bryglen** [comment]
how did you set your composer?

**Comment by RamzyVirani** [comment]
what do you mean by that? I installed yii2 via composer, executed below command and got error.

`php composer.phar require --prefer-dist bryglen/yii2-validators "*"`

**Comment by bryglen** [comment]
can you send over the composer.json?

**Comment by bryglen** [comment]
try to add 1.0.0 in the version instead of *. just added a new tag now.

**Comment by RamzyVirani** [comment]
Its working with 1.0.0... Thanks. :) 
I really appreciate your efforts. :+1:
